---
title: "Prepare Input for ensemble"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# Set path
if (Sys.info()["sysname"] == "Darwin"){
  mount_path <- "/Volumes/"
} else if (Sys.info()["sysname"] == "Linux"){
  mount_path <- "/mnt/"
} else {
  stop("Operating system is not supported")
}
```

```{r}
source("code/function_cells2labels.R")
source("code/function_save2tiff.R")
source("code/function_data2config.R")
```


Create 10 models to replicate CellSighter Paper
```{r}
if(!dir.exists(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass"))){
    dir.create(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass"))
  }

hm <- c("0"="Immune", "1"="Immune", "2"="Immune", "3"="Immune", "4"="Immune", "5"="Immune", "6"="Immune", "7"="Other", "8"="Immune", "9"="Immune", "10"="Immune", "11"="Immune", "12"="Immune", "13"="Other", "-1"="Other")

for (i in seq(1,10)){
  if(!dir.exists(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Model_",i))){
    dir.create(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Model_",i))
  }
  
  data2config(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Model_",i,"/"),
            # use data prepared by prepare_input_data.Rmd
            paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Input/"),
            # using information from param sweep analysis
            hierarchy_match = hm,
            crop_input_size = 20,
            epoch_max = 50,
            lr = 0.005,
            blacklist = c("DNA1","DNA2","HistoneH3"))
}

```
