---
title: "Prepare Parameter Sweep with 5-fold Validation part 2"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# Set path
if (Sys.info()["sysname"] == "Darwin"){
  mount_path <- "/Volumes/"
} else if (Sys.info()["sysname"] == "Linux"){
  mount_path <- "/mnt/"
} else {
  stop("Operating system is not supported")
}
```

```{r load, message=FALSE}
library(cytomapper)
library(stringr)
source("code/function_cells2labels.R")
source("code/function_save2tiff.R")
source("code/function_data2config.R")


sce <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/sce_selected.rds"))
images <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/all_images.rds"))
masks <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/all_masks.rds"))


hyperparams_1 <- read.csv("data/hyperparams.csv")
```


5-fold data preparation
```{r}
set.seed(080323)
# shuffle and assign one of k groups to am image in the dataset
k = 5
images_shuffled <- sample(unique(sce$image))
group <- c()
for (i in 1:length(images_shuffled)){
  group[images_shuffled[i]] <- i%%k+1
}

sce$k_fold_group <- group[sce$image]

table(sce$k_fold_group)
```

crop_input_size
```{r}
crop_input_size <- c(19,30,40)
```

epoch_max
```{r}
epoch_max <- c(50,80)
```

lr
```{r}
lr <- c(0.001,0.005)
```

hierarchy_match
```{r}
hierarchy_match <- list()


hierarchy_match[["A"]] <- c("0"="Immune", "1"="Immune", "2"="Immune", "3"="Immune", "4"="Immune", "5"="Immune", "6"="Immune", "7"="Other", "8"="Immune", "9"="Immune", "10"="Immune", "11"="Immune", "12"="Immune", "13"="Other", "-1"="Other")

hierarchy_match[["B"]] <- c("0"="B", "1"="B", "2"="T", "3"="T", "4"="Myeloid", "5"="Myeloid", "6"="Myeloid", "7"="Other", "8"="Myeloid", "9"="T", "10"="Myeloid", "11"="B", "12"="T", "13"="Tumor", "-1"="Other")

```


```{r}
if(!dir.exists(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/ParamSweep2"))){
    dir.create(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/ParamSweep2"))
  }

count <- 0
df <- data.frame()
for (crop in crop_input_size){
  for (epoch in epoch_max){
    for (l in lr){
      for (hm_name in names(hierarchy_match)){
        count <- count +1
        # select validation set by adding 1 to k from ParamSweep1
        cur_k <- (hyperparams_1[count,]$val_set + 1)%%k
        
        if(!dir.exists(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/ParamSweep2/Model_",count,"/"))){
          dir.create(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/ParamSweep2/Model_",count,"/"))
        }
        
        data2config(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/ParamSweep2/Model_",count,"/"),
            paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Input/"),
            train_set = unique(gsub(".tiff","",sce[,sce$k_fold_group != cur_k]$image)),
            val_set = unique(gsub(".tiff","",sce[,sce$k_fold_group == cur_k]$image)),
            crop_input_size = crop,
            epoch_max = epoch,
            lr = l,
            hierarchy_match = hierarchy_match[[hm_name]],
            blacklist = c("DNA1","DNA2","HistoneH3"))
        
        df <- rbind(df,list(Model_name = paste0("Model_",count), crop_input_size = crop, epoch_max = epoch, lr = l, hierarchy_match = hm_name, val_set = cur_k))
      }
    }
  }
}

write.csv(df, file="data/hyperparams2.csv")

```
