---
title: "Prepare Data for CellSighter Input"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# Set path
if (Sys.info()["sysname"] == "Darwin"){
  mount_path <- "/Volumes/"
} else if (Sys.info()["sysname"] == "Linux"){
  mount_path <- "/mnt/"
} else {
  stop("Operating system is not supported")
}
```

```{r load-libraries, message=FALSE}
library(cytomapper)
library(stringr)
source("code/function_cells2labels.R")
source("code/function_save2tiff.R")
source("code/function_data2config.R")


sce <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/sce_selected.rds"))
images <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/all_images.rds"))
masks <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/all_masks.rds"))

```
save images as .tiffs
```{r save-tiffs}
save2tiff(images,paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Input/"))
```

save masks as .tiffs
```{r}
save2tiff(masks,paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Input/"), masks = TRUE)
```

extract and save labels
```{r}
cells2labels(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Input/"),sce, "image", "cell_labels")
```


create config.json file
```{r}
data2config("./code/",paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Input/"),blacklist = c("DNA1,DNA2,HistoneH3"))

```

