---
title: "Visualize predictions"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# Set path
if (Sys.info()["sysname"] == "Darwin"){
  mount_path <- "/Volumes/"
} else if (Sys.info()["sysname"] == "Linux"){
  mount_path <- "/mnt/"
} else {
  stop("Operating system is not supported")
}
```


load data
```{r read-in-data}
library(stringr)
library(dplyr)
library(SummarizedExperiment)
library(readxl)
library(tidyverse)

# load sce
sce <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/sce_selected.rds"))

# prepare sce
sce$image <- sub(".tiff", "", sce$image)
sce$unique_id <- paste0(sce$image,sce$ObjectNumber)

# Read in masks
masks <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/all_masks.rds"))

# Read in images
images <- readRDS(paste0(mount_path,"immucan_volume/processed_data/Panel_1/cell_classification/all_images.rds"))

# read in results
df <- read.csv(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/merged_ensemble.csv"))
df$X <- NULL
```



```{r}
# create dictionary for translation between cell type id and cell type label
# create label to label-id dictionary, set unlabeled to -1
dic <- c()
labels <- sort(unique(sce$cell_labels))
labels <- labels[labels != "unlabelled"]

for (i in 1:length(labels)){
  dic[as.character(i-1)] <- labels[[i]]
}
dic["-1"] <- "unlabelled"

df$pred <- dic[as.character(df$pred)]
df$label <- dic[as.character(df$label)]

```

normalize images
```{r normalize-1}
images <- normalize(images, separateImages = TRUE)
images <- normalize(images, separateImages = TRUE,
                      inputRange = c(0, 0.2))

```


```{r define-markers-per-celltype}
cell_types <- names(metadata(sce)$colour_vectors$cell_types)

markers <- vector(mode = "list", length = length(cell_types))
names(markers) <- cell_types

markers[["B"]] <- c("CD20", "CD3")
markers[["BnT"]] <- c("CD20", "CD3")
markers[["plasma"]] <- c("CD38")
markers[["T_cell"]] <- c("CD3", "CD20")
markers[["CD4"]] <- c("CD4", "CD8a", "FOXP3")
markers[["CD8"]] <- c("CD4", "CD8a", "FOXP3")
markers[["Treg"]] <- c("CD4", "CD8a", "FOXP3")
markers[["DC"]] <- c("CD11c", "CD163", "CD68")
markers[["MacCD163"]] <- c("CD11c", "CD163", "CD68")
markers[["HLADR"]] <- c("CD11c", "CD163", "HLADR")
markers[["Neutrophil"]] <- c("CD15", "MPO")
markers[["NK"]] <- c("CD7", "CD3")
markers[["pDC"]] <- c("CD303")
markers[["Mural"]] <- c("SMA", "PDGFRb")
markers[["Tumor"]] <- c("Ecad", "CarbonicAnhydrase")
markers[["undefined"]] <- c("DNA1")

```


```{r}
for (cell_type in unique(df$label)){
  if(cell_type == "unlabelled") next
  correct_df <- df[(df$label == cell_type) & (df$pred == cell_type),]
  wrong_df <- df[(df$label != cell_type & df$label != "unlabelled") & (df$pred == cell_type),]
  correct_images <- names(sort(table(correct_df$image_id), decreasing = T))[1:10]
  wrong_images <- names(sort(table(wrong_df$image_id), decreasing = T))[1:10]
  
  # select masks and images
  correct_mask <- masks[correct_images]
  correct_images <- images[correct_images]
  
  wrong_mask <- masks[wrong_images]
  wrong_images <- images[wrong_images]
  
  correct_cells <- paste0(correct_df$image_id,correct_df$cell_id)
  wrong_cells <- paste0(wrong_df$image_id,wrong_df$cell_id)
  
  # select cells in sce
  correct_sce <- sce[,sce$unique_id %in% correct_cells]
  wrong_sce <- sce[,sce$unique_id %in% wrong_cells]
  
  
  cur_markers <- markers[[cell_type]]
  
  # generate folders if they do not already exist 
  if (!dir.exists(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Validation/",cell_type))) {
    dir.create(paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Validation/",cell_type), recursive = TRUE)
  }
  
  
  if (length(cur_markers) == 1) {
      cur_col <- "red"
      names(cur_col) <- cell_type
      cur_col <- list(cur_col)
      names(cur_col) <- "celltypes"
      # save correct
      plotPixels(image = correct_images, 
                object = correct_sce, 
                mask = correct_mask, 
                cell_id = "ObjectNumber",
                img_id = "image", 
                colour_by = cur_markers, 
                outline_by = "cell_labels",
                image_title = list(text = names(correct_images),
                                cex = 1), 
                colour = cur_col,
                save_plot = list(filename = paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Validation/"
                                                   ,cell_type,"/",cell_type,"_correct.png")))
      # save wrong
      plotPixels(image = wrong_images, 
                object = wrong_sce, 
                mask = wrong_mask, 
                cell_id = "ObjectNumber",
                img_id = "image", 
                colour_by = cur_markers, 
                outline_by = "cell_labels",
                image_title = list(text = names(wrong_images),
                                cex = 1), 
                colour = cur_col,
                save_plot = list(filename = paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Validation/"
                                                   ,cell_type,"/",cell_type,"_wrong.png")))
    } else {
      # save correct
        plotPixels(image = correct_images, 
                object = correct_sce, 
                mask = correct_mask, 
                cell_id = "ObjectNumber",
                img_id = "image", 
                colour_by = cur_markers, 
                outline_by = "cell_labels",
                image_title = list(text = names(correct_images),
                                cex = 1), 
                save_plot = list(filename = paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Validation/"
                                                   ,cell_type,"/",cell_type,"_correct.png")))
      # save wrong
      plotPixels(image = wrong_images, 
                object = wrong_sce, 
                mask = wrong_mask, 
                cell_id = "ObjectNumber",
                img_id = "image", 
                colour_by = cur_markers, 
                outline_by = "cell_labels",
                image_title = list(text = names(wrong_images),
                                cex = 1), 
                save_plot = list(filename = paste0(mount_path,"immucan_volume/processed_data/Panel_1/CellSighter/Multiclass/Validation/"
                                                   ,cell_type,"/",cell_type,"_wrong.png")))
    }
  }
  

```

```{r}
# quantify which cell are confused for which one
library(viridis)

df$unique_id <- paste0(df$image_id,df$cell_id)

comb <- as.data.frame(merge(colData(sce),df, by="unique_id"))

wrong <- comb[comb$cell_labels != comb$pred,] %>%
  filter(cell_labels != "unlabelled")


mat <- as.matrix(table(wrong$cell_labels,wrong$pred))
col_func <- colorRamp2(breaks = c(0,max(mat)), colors = c("white","Red"))

Heatmap(mat, col = viridis(100), row_title = "CellSIghter", column_title = "Cell Types",
        heatmap_legend_param = list(
          title = "Nr. Cells"))
```

# TODO: quantify if cell sighter is doing what supposed, ignoring spillover from surrounding cells
